[DEFAULT]
# Geant4可执行文件的路径
ExecutablePath = ./QF_ND5x2

# 最终输出的CSV数据文件名
OutputCSV = simulation_data.csv

# 扫描网格的密度 (例如100x100的网格)
GridDensity = 28

# 探测器尺寸的一半 (单位: mm), 你的探测器是 50x50 cm
DetectorHalfX = 250.0
DetectorHalfY = 250.0

# 为了避免极端边缘效应，扫描区域的比例
ScanAreaRatio = 0.85

# 粒子枪的Z轴位置 (单位: mm)
ParticleZPos = 100.0

RunSetCut_um = 0.01

# 对应 /run/beamOn 100
BeamOn = 100

# 对应 /gun/particle mu-
Particle = mu-

# 对应 /gun/energy 4 GeV
Energy = 4 GeV

# 对应 /gun/direction 0 -1 0
Direction = 0 -1 0

# 对应 /gun/position 中的固定Y值 (单位: cm)
GunPosY_cm = 10.0
