import os
import numpy as np
import time
import configparser
import argparse
import sys

def get_completed_points(csv_file):
    """通过计算CSV文件行数来确定已完成的点数"""
    if not os.path.exists(csv_file):
        return 0
    try:
        with open(csv_file, 'r') as f:
            # 减1是为了去掉表头行
            return max(0, len(f.readlines()) - 1)
    except Exception as e:
        print(f"警告：无法读取CSV文件 '{csv_file}'。错误: {e}。将从头开始。")
        return 0

def run_simulation():
    """主函数，负责管理整个模拟流程"""
    # --- 1. 解析命令行参数 ---
    parser = argparse.ArgumentParser(
        description="Geant4 Simulation Master Script with resume and range control.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument('--start', type=int, default=None, help="手动指定起始点索引 (从0开始)")
    parser.add_argument('--end', type=int, default=None, help="手动指定结束点索引 (不包含此索引)")
    args = parser.parse_args()

    # --- 2. 读取配置文件 ---
    config_file = 'config.ini'
    if not os.path.exists(config_file):
        print(f"错误：配置文件 '{config_file}' 不存在。请创建该文件。")
        sys.exit(1)
        
    config = configparser.ConfigParser()
    config.read(config_file)
    cfg = config['DEFAULT']

    # 读取所有配置参数
    try:
        executable_path = cfg.get('ExecutablePath')
        output_csv = cfg.get('OutputCSV')
        grid_density = cfg.getint('GridDensity')
        detector_half_x_cm = cfg.getfloat('DetectorHalfX_cm')
        detector_half_y_cm = cfg.getfloat('DetectorHalfY_cm')
        scan_ratio = cfg.getfloat('ScanAreaRatio')
        run_set_cut_um = cfg.getfloat('RunSetCut_um')
        beam_on = cfg.getint('BeamOn')
        particle = cfg.get('Particle')
        energy = cfg.get('Energy')
        direction = cfg.get('Direction')
        gun_pos_y_cm = cfg.getfloat('GunPosY_cm')
    except (configparser.NoOptionError, ValueError) as e:
        print(f"错误：配置文件 '{config_file}' 中缺少参数或参数格式错误。请检查。错误: {e}")
        sys.exit(1)

    temp_mac_file = "temp_run.mac"

    # --- 3. 生成所有扫描点坐标 ---
    # 注意：这里的x和y是物理上的真实坐标(x_true, y_true)
    scan_half_x_cm = detector_half_x_cm * scan_ratio
    scan_half_y_cm = detector_half_y_cm * scan_ratio
    
    x_true_points = np.linspace(-scan_half_x_cm, scan_half_x_cm, grid_density)
    y_true_points = np.linspace(-scan_half_y_cm, scan_half_y_cm, grid_density)
    
    # 使用 (y, x) 循环顺序，让扫描更直观 (逐行扫描)
    all_points = [(x, y) for y in y_true_points for x in x_true_points]
    total_points = len(all_points)

    # --- 4. 确定运行范围 ---
    if args.start is not None:
        # 手动模式
        start_index = args.start
        end_index = args.end if args.end is not None else total_points
        print(f"--- 手动模式：将运行点 {start_index} 到 {end_index-1} (共 {end_index - start_index} 个点) ---")
    else:
        # 自动续跑模式
        completed_points = get_completed_points(output_csv)
        start_index = completed_points
        end_index = total_points
        if start_index >= total_points:
            print(f"所有 {total_points} 个模拟点已完成！无需续跑。")
            return
        print(f"--- 自动续跑模式：检测到 {completed_points} 个已完成的点，从点 {start_index} 开始 ---")

    # --- 5. 准备主数据文件 (如果不存在则创建并写表头) ---
    if start_index == 0 and not os.path.exists(output_csv):
        print(f"主数据文件 '{output_csv}' 不存在，正在创建...")
        with open(output_csv, "w") as f:
            # 这个表头必须和你的C++代码输出顺序完全一致！
            f.write("x_true,y_true,EventID,DepositedEnergy_MeV,GeneratedPhotons,DetectedPMT1,DetectedPMT2,DetectedPMT3,DetectedPMT4\n")

    # --- 6. 主循环 ---
    points_to_run = all_points[start_index:end_index]
    if not points_to_run:
        print("本次没有需要运行的点。任务结束。")
        return
        
    start_time = time.time()
    
    try:
        for i, (x_true, y_true) in enumerate(points_to_run):
            current_global_index = start_index + i
            
            # --- 核心：应用您的坐标系规则 ---
            # Geant4的X位置 = y_true
            # Geant4的Y位置 = 固定的Y值
            # Geant4的Z位置 = x_true
            gun_pos_x_cm = y_true
            gun_pos_z_cm = x_true

            # 生成临时的宏文件，完全复刻您的run.mac
            mac_content = f"""
# --- Macro file generated by run_master.py ---
/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/setCut {run_set_cut_um} um

/gun/particle {particle}
/gun/energy {energy}
/gun/position {gun_pos_x_cm:.4f} {gun_pos_y_cm:.4f} {gun_pos_z_cm:.4f} cm
/gun/direction {direction}

/run/printProgress 50
/run/beamOn {beam_on}
# --- End of generated macro ---
"""
            with open(temp_mac_file, "w") as f:
                f.write(mac_content)
            
            # 执行Geant4模拟 (屏蔽输出，保持界面干净)
            # 在Windows上使用 '> NUL 2>&1'，在Linux/macOS上使用 '> /dev/null 2>&1'
            redirect_output = '> /dev/null 2>&1' if os.name != 'nt' else '> NUL 2>&1'
            command = f"{executable_path} {temp_mac_file} {redirect_output}"
            os.system(command)
            
            # 打印进度
            if (i + 1) % 10 == 0 or (i + 1) == len(points_to_run):
                elapsed = time.time() - start_time
                points_done_this_session = i + 1
                avg_time_per_point = elapsed / points_done_this_session
                remaining_points_this_session = len(points_to_run) - points_done_this_session
                eta_seconds = remaining_points_this_session * avg_time_per_point
                
                print(f"进度: {current_global_index + 1}/{total_points} | "
                      f"本次已运行 {points_done_this_session}/{len(points_to_run)} | "
                      f"预计剩余: {int(eta_seconds // 60)}m {int(eta_seconds % 60)}s")

    except KeyboardInterrupt:
        print("\n\n--- 检测到 Ctrl+C，程序已安全停止。下次运行可自动续跑。 ---")
    except Exception as e:
        print(f"\n发生未知错误: {e}")
    finally:
        if os.path.exists(temp_mac_file):
            os.remove(temp_mac_file)
        print("任务结束。")

if __name__ == "__main__":
    run_simulation()
